language: python
python:
  - "2.7"
  - "3.4"
sudo:
  - "required"
before_install:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get update"
  - "sudo apt-get install postfix"
  - "sudo service postfix start"
  - "npm -g install npm@next"
install:
  - "pip install -r requirements.txt"
  - "npm install"
  - "jspm install"
  - "gulp"
script:
  - "python svenv/manage.py test svenv"
  - "gulp test"
